version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    ports:
      - 3333:3333
    depends_on:
      - mongodb
    networks:
      - app-network

  web:
    build: ./web
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
     